//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MetalLiqViajes_Forms.com.terpel.movilidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegratorSoap", Namespace="http://Flotas/")]
    public partial class Integrator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaEDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarRestriccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaTranRestriccionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Integrator() {
            this.Url = global::MetalLiqViajes_Forms.Properties.Settings.Default.MetalLiqViajes_Forms_com_terpel_movilidad_Integrator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaVentasCompletedEventHandler ConsultaVentasCompleted;
        
        /// <remarks/>
        public event ConsultaEDSCompletedEventHandler ConsultaEDSCompleted;
        
        /// <remarks/>
        public event cargarRestriccionesCompletedEventHandler cargarRestriccionesCompleted;
        
        /// <remarks/>
        public event consultaTranRestriccionCompletedEventHandler consultaTranRestriccionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Flotas/ConsultaVentas", RequestNamespace="http://Flotas/", ResponseNamespace="http://Flotas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VentasFlotaResponse[] ConsultaVentas(string consulta) {
            object[] results = this.Invoke("ConsultaVentas", new object[] {
                        consulta});
            return ((VentasFlotaResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaVentasAsync(string consulta) {
            this.ConsultaVentasAsync(consulta, null);
        }
        
        /// <remarks/>
        public void ConsultaVentasAsync(string consulta, object userState) {
            if ((this.ConsultaVentasOperationCompleted == null)) {
                this.ConsultaVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaVentasOperationCompleted);
            }
            this.InvokeAsync("ConsultaVentas", new object[] {
                        consulta}, this.ConsultaVentasOperationCompleted, userState);
        }
        
        private void OnConsultaVentasOperationCompleted(object arg) {
            if ((this.ConsultaVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaVentasCompleted(this, new ConsultaVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Flotas/ConsultaEDS", RequestNamespace="http://Flotas/", ResponseNamespace="http://Flotas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CosultaEDSFlota[] ConsultaEDS(string codigo) {
            object[] results = this.Invoke("ConsultaEDS", new object[] {
                        codigo});
            return ((CosultaEDSFlota[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaEDSAsync(string codigo) {
            this.ConsultaEDSAsync(codigo, null);
        }
        
        /// <remarks/>
        public void ConsultaEDSAsync(string codigo, object userState) {
            if ((this.ConsultaEDSOperationCompleted == null)) {
                this.ConsultaEDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaEDSOperationCompleted);
            }
            this.InvokeAsync("ConsultaEDS", new object[] {
                        codigo}, this.ConsultaEDSOperationCompleted, userState);
        }
        
        private void OnConsultaEDSOperationCompleted(object arg) {
            if ((this.ConsultaEDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaEDSCompleted(this, new ConsultaEDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Flotas/cargarRestricciones", RequestNamespace="http://Flotas/", ResponseNamespace="http://Flotas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaRestricciones cargarRestricciones(string cargas, ContextoTransaccionalTipo ContextoTransaccionalTipo) {
            object[] results = this.Invoke("cargarRestricciones", new object[] {
                        cargas,
                        ContextoTransaccionalTipo});
            return ((RespuestaRestricciones)(results[0]));
        }
        
        /// <remarks/>
        public void cargarRestriccionesAsync(string cargas, ContextoTransaccionalTipo ContextoTransaccionalTipo) {
            this.cargarRestriccionesAsync(cargas, ContextoTransaccionalTipo, null);
        }
        
        /// <remarks/>
        public void cargarRestriccionesAsync(string cargas, ContextoTransaccionalTipo ContextoTransaccionalTipo, object userState) {
            if ((this.cargarRestriccionesOperationCompleted == null)) {
                this.cargarRestriccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarRestriccionesOperationCompleted);
            }
            this.InvokeAsync("cargarRestricciones", new object[] {
                        cargas,
                        ContextoTransaccionalTipo}, this.cargarRestriccionesOperationCompleted, userState);
        }
        
        private void OncargarRestriccionesOperationCompleted(object arg) {
            if ((this.cargarRestriccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarRestriccionesCompleted(this, new cargarRestriccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Flotas/consultaTranRestriccion", RequestNamespace="http://Flotas/", ResponseNamespace="http://Flotas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public consultaTranRestriccionRes consultaTranRestriccion(string idTx) {
            object[] results = this.Invoke("consultaTranRestriccion", new object[] {
                        idTx});
            return ((consultaTranRestriccionRes)(results[0]));
        }
        
        /// <remarks/>
        public void consultaTranRestriccionAsync(string idTx) {
            this.consultaTranRestriccionAsync(idTx, null);
        }
        
        /// <remarks/>
        public void consultaTranRestriccionAsync(string idTx, object userState) {
            if ((this.consultaTranRestriccionOperationCompleted == null)) {
                this.consultaTranRestriccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaTranRestriccionOperationCompleted);
            }
            this.InvokeAsync("consultaTranRestriccion", new object[] {
                        idTx}, this.consultaTranRestriccionOperationCompleted, userState);
        }
        
        private void OnconsultaTranRestriccionOperationCompleted(object arg) {
            if ((this.consultaTranRestriccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaTranRestriccionCompleted(this, new consultaTranRestriccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class VentasFlotaResponse {
        
        private int reciboField;
        
        private System.DateTime fechaField;
        
        private string placaField;
        
        private string productoField;
        
        private decimal dineroField;
        
        private decimal volumenField;
        
        private int kilometrajeField;
        
        private int codEdsField;
        
        /// <remarks/>
        public int Recibo {
            get {
                return this.reciboField;
            }
            set {
                this.reciboField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Dinero {
            get {
                return this.dineroField;
            }
            set {
                this.dineroField = value;
            }
        }
        
        /// <remarks/>
        public decimal Volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        public int Kilometraje {
            get {
                return this.kilometrajeField;
            }
            set {
                this.kilometrajeField = value;
            }
        }
        
        /// <remarks/>
        public int CodEds {
            get {
                return this.codEdsField;
            }
            set {
                this.codEdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class ConsultaCarga {
        
        private string codErrorField;
        
        private int consecutivoField;
        
        private string descErrorField;
        
        /// <remarks/>
        public string codError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
            }
        }
        
        /// <remarks/>
        public int consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
            }
        }
        
        /// <remarks/>
        public string descError {
            get {
                return this.descErrorField;
            }
            set {
                this.descErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class consultaTranRestriccionRes {
        
        private ContextoRespuestaTipo contextoRespuestaField;
        
        private ConsultaCarga[] consultaCargaField;
        
        private FalloTipo erroresField;
        
        /// <remarks/>
        public ContextoRespuestaTipo contextoRespuesta {
            get {
                return this.contextoRespuestaField;
            }
            set {
                this.contextoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public ConsultaCarga[] consultaCarga {
            get {
                return this.consultaCargaField;
            }
            set {
                this.consultaCargaField = value;
            }
        }
        
        /// <remarks/>
        public FalloTipo errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class ContextoRespuestaTipo {
        
        private string idTxField;
        
        private string codEstadoTxField;
        
        private System.DateTime fechaTxField;
        
        /// <remarks/>
        public string idTx {
            get {
                return this.idTxField;
            }
            set {
                this.idTxField = value;
            }
        }
        
        /// <remarks/>
        public string codEstadoTx {
            get {
                return this.codEstadoTxField;
            }
            set {
                this.codEstadoTxField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaTx {
            get {
                return this.fechaTxField;
            }
            set {
                this.fechaTxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class FalloTipo {
        
        private ContextoRespuestaTipo contextoRespuestaField;
        
        private ErrorTipo[] erroresField;
        
        /// <remarks/>
        public ContextoRespuestaTipo ContextoRespuesta {
            get {
                return this.contextoRespuestaField;
            }
            set {
                this.contextoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public ErrorTipo[] errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class ErrorTipo {
        
        private string codErrorField;
        
        private string valDescErrorField;
        
        private string valDescErrorTecnicoField;
        
        /// <remarks/>
        public string codError {
            get {
                return this.codErrorField;
            }
            set {
                this.codErrorField = value;
            }
        }
        
        /// <remarks/>
        public string valDescError {
            get {
                return this.valDescErrorField;
            }
            set {
                this.valDescErrorField = value;
            }
        }
        
        /// <remarks/>
        public string valDescErrorTecnico {
            get {
                return this.valDescErrorTecnicoField;
            }
            set {
                this.valDescErrorTecnicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class RespuestaRestricciones {
        
        private ContextoRespuestaTipo contextoRespuestaField;
        
        private string msjEnProcesoField;
        
        private FalloTipo erroresField;
        
        /// <remarks/>
        public ContextoRespuestaTipo contextoRespuesta {
            get {
                return this.contextoRespuestaField;
            }
            set {
                this.contextoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string msjEnProceso {
            get {
                return this.msjEnProcesoField;
            }
            set {
                this.msjEnProcesoField = value;
            }
        }
        
        /// <remarks/>
        public FalloTipo errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class ContextoTransaccionalTipo {
        
        private string idTxField;
        
        private string idUsuarioAplicacionField;
        
        private string valNombreCanalField;
        
        private string valClaveUsuarioAplicacionField;
        
        /// <remarks/>
        public string idTx {
            get {
                return this.idTxField;
            }
            set {
                this.idTxField = value;
            }
        }
        
        /// <remarks/>
        public string idUsuarioAplicacion {
            get {
                return this.idUsuarioAplicacionField;
            }
            set {
                this.idUsuarioAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string valNombreCanal {
            get {
                return this.valNombreCanalField;
            }
            set {
                this.valNombreCanalField = value;
            }
        }
        
        /// <remarks/>
        public string valClaveUsuarioAplicacion {
            get {
                return this.valClaveUsuarioAplicacionField;
            }
            set {
                this.valClaveUsuarioAplicacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Flotas/")]
    public partial class CosultaEDSFlota {
        
        private int codEDSField;
        
        private string nombreField;
        
        private string tipoField;
        
        private string regionalField;
        
        private System.DateTime actualizadaField;
        
        /// <remarks/>
        public int CodEDS {
            get {
                return this.codEDSField;
            }
            set {
                this.codEDSField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string Regional {
            get {
                return this.regionalField;
            }
            set {
                this.regionalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Actualizada {
            get {
                return this.actualizadaField;
            }
            set {
                this.actualizadaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConsultaVentasCompletedEventHandler(object sender, ConsultaVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VentasFlotaResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VentasFlotaResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConsultaEDSCompletedEventHandler(object sender, ConsultaEDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaEDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaEDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CosultaEDSFlota[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CosultaEDSFlota[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cargarRestriccionesCompletedEventHandler(object sender, cargarRestriccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarRestriccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarRestriccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaRestricciones Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaRestricciones)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaTranRestriccionCompletedEventHandler(object sender, consultaTranRestriccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaTranRestriccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaTranRestriccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaTranRestriccionRes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaTranRestriccionRes)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591